/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   获取待处理工单个数接口
   Get  numbers of pending list API

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  查询待处理工单个数
public class GetUntreatedIssueCountByCustomerIdRequest:JdCloudRequest
{
    /// 客户的pin
    var pin:String


    public init(regionId: String,pin:String){
        self.pin = pin
        super.init(regionId: regionId)
    }


    enum GetUntreatedIssueCountByCustomerIdRequestRequestCodingKeys: String, CodingKey {
        case pin
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: GetUntreatedIssueCountByCustomerIdRequestRequestCodingKeys.self)
        try container.encode(pin, forKey: .pin)

    }
}
