/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Mount-Target
   挂载目标相关接口。

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  - 为一个文件系统创建一个挂载目标。通过这个挂载目标,你可以挂载将一个文件系统挂载到主机实例上。
      ///       /// - 创建一个挂载目标，为这个挂载目标分配一个Id
      ///       /// 
@objc(CreateMountTargetRequest)
public class CreateMountTargetRequest:JdCloudRequest
{
    /// 创建挂载目标的文件系统
    var fileSystemId:String

    /// 子网id
    var subnetId:String

    /// vpcId
    var vpcId:String

    /// 安全组id
    var securityGroupId:String

    /// 幂等性参数(只支持数字、大小写字母，且不能超过64字符)
    var clientToken:String


    public init(regionId: String,fileSystemId:String,subnetId:String,vpcId:String,securityGroupId:String,clientToken:String){
        self.fileSystemId = fileSystemId
        self.subnetId = subnetId
        self.vpcId = vpcId
        self.securityGroupId = securityGroupId
        self.clientToken = clientToken
        super.init(regionId: regionId)
    }


    enum CreateMountTargetRequestRequestCodingKeys: String, CodingKey {
        case fileSystemId
        case subnetId
        case vpcId
        case securityGroupId
        case clientToken
    }

    public override func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CreateMountTargetRequestRequestCodingKeys.self)
        try encoderContainer.encode(fileSystemId, forKey: .fileSystemId)
        try encoderContainer.encode(subnetId, forKey: .subnetId)
        try encoderContainer.encode(vpcId, forKey: .vpcId)
        try encoderContainer.encode(securityGroupId, forKey: .securityGroupId)
        try encoderContainer.encode(clientToken, forKey: .clientToken)

    }
}
