/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   JDCLOUD BILLING Services API
   用户中心消费管理查询API接口

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  查询消费总览
@objc(QueryConsumptionOverViewRequest)
public class QueryConsumptionOverViewRequest:JdCloudRequest
{
    /// TimeType
    var timeType:Int

    /// StartTime
    var startTime:String

    /// EndTime
    var endTime:String


    public init(regionId: String,timeType:Int,startTime:String,endTime:String){
        self.timeType = timeType
        self.startTime = startTime
        self.endTime = endTime
        super.init(regionId: regionId)
    }


    enum QueryConsumptionOverViewRequestRequestCodingKeys: String, CodingKey {
        case timeType
        case startTime
        case endTime
    }

    public override func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: QueryConsumptionOverViewRequestRequestCodingKeys.self)
        try encoderContainer.encode(timeType, forKey: .timeType)
        try encoderContainer.encode(startTime, forKey: .startTime)
        try encoderContainer.encode(endTime, forKey: .endTime)

    }
}
