
pod trunk push  JDCloudSDKCr.podspec --allow-warnings
pod trunk push  JDCloudSDKClouddnsservice.podspec --allow-warnings
pod trunk push  JDCloudSDKContainerregistry.podspec --allow-warnings
pod trunk push  JDCloudSDKCps.podspec --allow-warnings 
pod trunk push  JDCloudSDKDatastar.podspec --allow-warnings
pod trunk push  JDCloudSDKFunction.podspec --allow-warnings 
pod trunk push  JDCloudSDKHttpdns.podspec --allow-warnings
pod trunk push  JDCloudSDKIam.podspec --allow-warnings 
pod trunk push  JDCloudSDKIas.podspec --allow-warnings 
pod trunk push  JDCloudSDKIpanti.podspec --allow-warnings
pod trunk push  JDCloudSDKIothub.podspec --allow-warnings 
pod trunk push  JDCloudSDKJdfusion.podspec  --allow-warnings 
pod trunk push  JDCloudSDKJdw.podspec --allow-warnings 
pod trunk push  JDCloudSDKJke.podspec --allow-warnings
pod trunk push  JDCloudSDKKms.podspec --allow-warnings 
pod trunk push  JDCloudSDKLive.podspec --allow-warnings
pod trunk push  JDCloudSDKMongodb.podspec --allow-warnings 
pod trunk push  JDCloudSDKMonitor.podspec --allow-warnings
pod trunk push  JDCloudSDKMps.podspec --allow-warnings
pod trunk push  JDCloudSDKNc.podspec --allow-warnings
pod trunk push  JDCloudSDKOss.podspec  --allow-warnings  
pod trunk push  JDCloudSDKOssopenapi.podspec  --allow-warnings
pod trunk push  JDCloudSDKRds.podspec  --allow-warnings 
pod trunk push  JDCloudSDKRedis.podspec  --allow-warnings 
pod trunk push  JDCloudSDKSop.podspec  --allow-warnings  
pod trunk push  JDCloudSDKStreambus.podspec  --allow-warnings
pod trunk push  JDCloudSDKStreamcomputer.podspec  --allow-warnings 
pod trunk push  JDCloudSDKXdata.podspec  --allow-warnings 
