/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Redis Instance API
   缓存Redis实例的创建、删除、修改基本信息、设置密码、变配、列表查询、备份、配置参数接口

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  重置缓存Redis实例的密码，可为空
@objc(ResetCacheInstancePasswordRequest)
public class ResetCacheInstancePasswordRequest:JdCloudRequest
{
    /// 密码，为空即为免密，不少于8字符不超过16字符
    var password:String?

    /// 缓存Redis实例ID，是访问实例的唯一标识
    var cacheInstanceId:String


    public init(regionId: String,cacheInstanceId:String){
        self.cacheInstanceId = cacheInstanceId
        super.init(regionId: regionId)
    }


    enum ResetCacheInstancePasswordRequestRequestCodingKeys: String, CodingKey {
        case password
        case cacheInstanceId
    }

    public override func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: ResetCacheInstancePasswordRequestRequestCodingKeys.self)
        try encoderContainer.encode(password, forKey: .password)
        try encoderContainer.encode(cacheInstanceId, forKey: .cacheInstanceId)

    }
}
