/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   实例管理-IP黑名单
   API related to WafMaliciousIp

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  修改IP黑名单规则
public class ModifyMaliciousIpRequest:JdCloudRequest
{
    /// 添加IP黑名单所需基本信息。
    var maliciousIp:MaliciousIp

    /// waf 实例id
    var instanceId:String

    /// IP黑名单规则id
    var ruleId:String


    public init(regionId: String,maliciousIp:MaliciousIp,instanceId:String,ruleId:String){
        self.maliciousIp = maliciousIp
        self.instanceId = instanceId
        self.ruleId = ruleId
        super.init(regionId: regionId)
    }


    enum ModifyMaliciousIpRequestRequestCodingKeys: String, CodingKey {
        case maliciousIp
        case instanceId
        case ruleId
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: ModifyMaliciousIpRequestRequestCodingKeys.self)
        try container.encode(maliciousIp, forKey: .maliciousIp)
        try container.encode(instanceId, forKey: .instanceId)
        try container.encode(ruleId, forKey: .ruleId)

    }
}
