/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   
   

   
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation

///  vmKeypairCollection
@objc(VmKeypairCollection)
public class VmKeypairCollection:NSObject,Codable{
    /// Keypairs
    var keypairs:[KeypairInfo?]?



    public override init(){
            super.init()
    }

    enum VmKeypairCollectionCodingKeys: String, CodingKey {
        case keypairs
    }


    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: VmKeypairCollectionCodingKeys.self)
        if decoderContainer.contains(.keypairs)
        {
            self.keypairs = try decoderContainer.decode([KeypairInfo?]?.self, forKey: .keypairs)
        }
    }
}
public extension VmKeypairCollection{
    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: VmKeypairCollectionCodingKeys.self)
         try encoderContainer.encode(keypairs, forKey: .keypairs)
    }
}
