/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   
   

   
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation

///  certInfo
@objc(CertInfo)
public class CertInfo:NSObject,Codable{
    /// 通用名称
    var domain:String?
    /// 证书生效时间
    var from:String?
    /// 证书到期时间
    var to:String?
    /// 证书组织
    var user:String?
    /// 加密算法
    var sigAlgName:String?
    /// 颁发者
    var issuer:String?



    public override init(){
            super.init()
    }

    enum CertInfoCodingKeys: String, CodingKey {
        case domain
        case from
        case to
        case user
        case sigAlgName
        case issuer
    }


    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: CertInfoCodingKeys.self)
        if decoderContainer.contains(.domain)
        {
            self.domain = try decoderContainer.decode(String?.self, forKey: .domain)
        }
        if decoderContainer.contains(.from)
        {
            self.from = try decoderContainer.decode(String?.self, forKey: .from)
        }
        if decoderContainer.contains(.to)
        {
            self.to = try decoderContainer.decode(String?.self, forKey: .to)
        }
        if decoderContainer.contains(.user)
        {
            self.user = try decoderContainer.decode(String?.self, forKey: .user)
        }
        if decoderContainer.contains(.sigAlgName)
        {
            self.sigAlgName = try decoderContainer.decode(String?.self, forKey: .sigAlgName)
        }
        if decoderContainer.contains(.issuer)
        {
            self.issuer = try decoderContainer.decode(String?.self, forKey: .issuer)
        }
    }
}
public extension CertInfo{
    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CertInfoCodingKeys.self)
         try encoderContainer.encode(domain, forKey: .domain)
         try encoderContainer.encode(from, forKey: .from)
         try encoderContainer.encode(to, forKey: .to)
         try encoderContainer.encode(user, forKey: .user)
         try encoderContainer.encode(sigAlgName, forKey: .sigAlgName)
         try encoderContainer.encode(issuer, forKey: .issuer)
    }
}
