/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   IP Resource APIs
   Anti DDoS Basic IP Resource APIs

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore

/// 查询基础防护已防护公网 IP 安全信息, 支持 ipv4 和 ipv6
@objc(DescribeIpSafetyInfoResult)
public class DescribeIpSafetyInfoResult:NSObject,JdCloudResult
{
    /// Data
    var data:IpSafetyInfo?



    public override init(){
        super.init()
    }

    enum DescribeIpSafetyInfoResultCodingKeys: String, CodingKey {
        case data
    }

    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: DescribeIpSafetyInfoResultCodingKeys.self)
        if decoderContainer.contains(.data)
        {
            self.data = try decoderContainer.decode(IpSafetyInfo?.self, forKey: .data)
        }
    }
}
public extension DescribeIpSafetyInfoResult{
    func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: DescribeIpSafetyInfoResultCodingKeys.self)
        try encoderContainer.encode(data, forKey: .data)
    }
}
