/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   用户中心接口
   用户中心接口

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  获取用户资源权限
public class DescribePrivilegeRequest:JdCloudRequest
{
    /// 用户pin
    var pin:String

    /// 产品线
    var appCode:String

    /// 具体产品
    var serviceCode:String


    public init(regionId: String,pin:String,appCode:String,serviceCode:String){
        self.pin = pin
        self.appCode = appCode
        self.serviceCode = serviceCode
        super.init(regionId: regionId)
    }


    enum DescribePrivilegeRequestRequestCodingKeys: String, CodingKey {
        case pin
        case appCode
        case serviceCode
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: DescribePrivilegeRequestRequestCodingKeys.self)
        try container.encode(pin, forKey: .pin)
        try container.encode(appCode, forKey: .appCode)
        try container.encode(serviceCode, forKey: .serviceCode)

    }
}
