/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   JOB相关API
   流计算作业相关信息接口

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore

/// 添加或者更新job
@objc(AddOrUpdateJobResult)
public class AddOrUpdateJobResult:NSObject,JdCloudResult
{
    /// 成功结果对象
    var okInfo:OkInfo?



    public override init(){
        super.init()
    }

    enum AddOrUpdateJobResultCodingKeys: String, CodingKey {
        case okInfo
    }

    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: AddOrUpdateJobResultCodingKeys.self)
        self.okInfo = try decoderContainer.decode(OkInfo?.self, forKey: .okInfo)
    }
}
public extension AddOrUpdateJobResult{
    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: AddOrUpdateJobResultCodingKeys.self)
        try encoderContainer.encode(okInfo, forKey: .okInfo)
    }
}
