/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Monitoring Rules APIs
   云监控规则相关接口，提供创建、查询、修改、删除监控规则等功能

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  查询报警历史
      ///       /// 检索条件组合优先级从高到低为
      ///       /// 1. alarmId
      ///       /// 2. serviceCode
      ///       /// 2.1 serviceCode + resourceId
      ///       /// 2.2 serviceCode + resourceIds
      ///       /// 3. serviceCodes
      ///       /// 4. 用户所有规则
@objc(DescribeAlarmHistoryRequest)
public class DescribeAlarmHistoryRequest:JdCloudRequest
{
    /// 当前所在页，默认为1
    var pageNumber:Int64?

    /// 页面大小，默认为20；取值范围[1, 100]
    var pageSize:Int64?

    /// 产品线
    var serviceCode:String?

    /// 资源Id
    var resourceId:String?

    /// resourceId列表
    var resourceIdList:[String?]?

    /// 规则Id
    var alarmId:String?

    /// 正在报警, 取值为1
    var alarming:Int64?

    /// 产品线列表
    var serviceCodeList:[String?]?

    /// 开始时间
    var startTime:String?

    /// 结束时间
    var endTime:String?

    /// 规则类型,默认查询1， 1表示资源监控，6表示站点监控,7表示可用性监控
    var ruleType:Int64?

    /// 服务码或资源Id列表
      /// filter name 为serviceCodes表示查询多个产品线的规则
      /// filter name 为resourceIds表示查询多个资源的规则
    var filters:[Filter?]?




    enum DescribeAlarmHistoryRequestRequestCodingKeys: String, CodingKey {
        case pageNumber
        case pageSize
        case serviceCode
        case resourceId
        case resourceIdList
        case alarmId
        case alarming
        case serviceCodeList
        case startTime
        case endTime
        case ruleType
        case filters
    }

    public override func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: DescribeAlarmHistoryRequestRequestCodingKeys.self)
        try encoderContainer.encode(pageNumber, forKey: .pageNumber)
        try encoderContainer.encode(pageSize, forKey: .pageSize)
        try encoderContainer.encode(serviceCode, forKey: .serviceCode)
        try encoderContainer.encode(resourceId, forKey: .resourceId)
        try encoderContainer.encode(resourceIdList, forKey: .resourceIdList)
        try encoderContainer.encode(alarmId, forKey: .alarmId)
        try encoderContainer.encode(alarming, forKey: .alarming)
        try encoderContainer.encode(serviceCodeList, forKey: .serviceCodeList)
        try encoderContainer.encode(startTime, forKey: .startTime)
        try encoderContainer.encode(endTime, forKey: .endTime)
        try encoderContainer.encode(ruleType, forKey: .ruleType)
        try encoderContainer.encode(filters, forKey: .filters)

    }
}
