/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Function OpenAPI
   

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  创建版本
@objc(CreateVersionRequest)
public class CreateVersionRequest:JdCloudRequest
{
    /// 版本描述
    var descriptionValue:String?

    /// 函数名称
    var functionName:String


    public init(regionId: String,functionName:String){
        self.functionName = functionName
        super.init(regionId: regionId)
    }


    enum CreateVersionRequestRequestCodingKeys: String, CodingKey {
        case descriptionValue = "description"
        case functionName
    }

    public override func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: CreateVersionRequestRequestCodingKeys.self)
        try encoderContainer.encode(descriptionValue, forKey: .descriptionValue)
        try encoderContainer.encode(functionName, forKey: .functionName)

    }
}
