/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   
   

   
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation

///  permission
@objc(Permission)
public class Permission:NSObject,Codable{
    /// userId
    var userId:String?
    /// permission, [SUB, PUB, PUBSUB]
    var permissionValue:String?



    public override init(){
            super.init()
    }

    enum PermissionCodingKeys: String, CodingKey {
        case userId
        case permissionValue = "permission"
    }


    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: PermissionCodingKeys.self)
        if decoderContainer.contains(.userId)
        {
            self.userId = try decoderContainer.decode(String?.self, forKey: .userId)
        }
        if decoderContainer.contains(.permissionValue)
        {
            self.permissionValue = try decoderContainer.decode(String?.self, forKey: .permissionValue)
        }
    }
}
public extension Permission{
    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: PermissionCodingKeys.self)
         try encoderContainer.encode(userId, forKey: .userId)
         try encoderContainer.encode(permissionValue, forKey: .permissionValue)
    }
}
