/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   JDCLOUD 攻击信息 API
   态势感知定向攻击相关信息接口

   OpenAPI spec version: v2
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  查询威胁事件详情接口
public class QueryThreatEventRequest:JdCloudRequest
{
    /// threatEvent事件ID
    var threatEventId:String


    public init(regionId: String,threatEventId:String){
        self.threatEventId = threatEventId
        super.init(regionId: regionId)
    }


    enum QueryThreatEventRequestRequestCodingKeys: String, CodingKey {
        case threatEventId
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: QueryThreatEventRequestRequestCodingKeys.self)
        try container.encode(threatEventId, forKey: .threatEventId)

    }
}
