/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   nodeGroup
   节点组相关接口

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore


///  调整节点组实例数量
public class SetNodeGroupSizeRequest:JdCloudRequest
{
    /// 创建集群请求参数模型
    var expectCount:Int?

    /// 节点组 ID
    var nodeGroupId:String


    public init(regionId: String,nodeGroupId:String){
        self.nodeGroupId = nodeGroupId
        super.init(regionId: regionId)
    }


    enum SetNodeGroupSizeRequestRequestCodingKeys: String, CodingKey {
        case expectCount
        case nodeGroupId
    }

    public override func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: SetNodeGroupSizeRequestRequestCodingKeys.self)
        try container.encode(expectCount, forKey: .expectCount)
        try container.encode(nodeGroupId, forKey: .nodeGroupId)

    }
}
