/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   Resource
   Interface of Resource

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore

/// 查询支持的资源列表
@objc(DescribeResourceTypeListResult)
public class DescribeResourceTypeListResult:NSObject,JdCloudResult
{
    /// ResourceTypeList
    var resourceTypeList:[DescribeResourceTypeListItem?]?

    /// TotalCount
    var totalCount:Int64?



    public override init(){
        super.init()
    }

    enum DescribeResourceTypeListResultCodingKeys: String, CodingKey {
        case resourceTypeList
        case totalCount
    }

    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: DescribeResourceTypeListResultCodingKeys.self)
        if decoderContainer.contains(.resourceTypeList)
        {
            self.resourceTypeList = try decoderContainer.decode([DescribeResourceTypeListItem?]?.self, forKey: .resourceTypeList)
        }
        if decoderContainer.contains(.totalCount)
        {
            self.totalCount = try decoderContainer.decode(Int64?.self, forKey: .totalCount)
        }
    }
}
public extension DescribeResourceTypeListResult{
    public func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: DescribeResourceTypeListResultCodingKeys.self)
        try encoderContainer.encode(resourceTypeList, forKey: .resourceTypeList)
        try encoderContainer.encode(totalCount, forKey: .totalCount)
    }
}
