/* Copyright 2018 JDCLOUD.COM

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http:#www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   DeadLetter
   死信队列相关接口

   OpenAPI spec version: v1
   Contact: 

   NOTE: This class is auto generated by the jdcloud code generator program.
 */


import Foundation
import JDCloudSDKCore

/// 重发死信消息
@objc(ResendDeadLettersResult)
public class ResendDeadLettersResult:NSObject,JdCloudResult
{
    /// MessageIds
    var messageIds:[String?]?



    public override init(){
        super.init()
    }

    enum ResendDeadLettersResultCodingKeys: String, CodingKey {
        case messageIds
    }

    required public init(from decoder: Decoder) throws {
        let decoderContainer = try decoder.container(keyedBy: ResendDeadLettersResultCodingKeys.self)
        if decoderContainer.contains(.messageIds)
        {
            self.messageIds = try decoderContainer.decode([String?]?.self, forKey: .messageIds)
        }
    }
}
public extension ResendDeadLettersResult{
    func encode(to encoder: Encoder) throws {
        var encoderContainer = encoder.container(keyedBy: ResendDeadLettersResultCodingKeys.self)
        try encoderContainer.encode(messageIds, forKey: .messageIds)
    }
}
